theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
scrolloff = 8

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true
