# Markdown
[[language]]
name = "markdown"
language-server = { command = "ltex-ls" }
rulers = [80]

# Rust
[[language]]
name = "rust"

[language.config]
checkOnSave.enabled = false
rustfmt.extraArgs = [ "+nightly", ]

